### ISSUE TITLE
Add confirmation when updating a policy without members field via curl

### ISSUE THREAD

**Issue by susanev** [chef/automate#1519]
## Overview
When using curl to update a policy, if a user does not include the members field (meaning they will remove all members), first provide a confirmation that the user intends this action.

Something like...`Policy update missing members field, which will cause all current members to be removed. Do you want to update the policy and remove all current members? (yes/no)` with `no` being bold.

Feel free to refine the messaging and work with @susanev  on final wording.

**Comment by srenatus** [comment]
Curl api requests are usually stateless. To achieve something similar, requests without members could be denied unless they also provide some "i really want this" boolean field.... But I'd rather not go there. Let's discuss this on Monday =)

**Comment by susanev** [comment]
Sure! I'm pretty much just blindly moving this from jira. Happy to close any of them out.

**Comment by srenatus** [comment]
> Should we require the members field instead?

If the last member is deleted (only happens for local teams, local users, tokens getting deleted), we'd keep the policy without any members, too, I believe. So, policies without members would not be a forbidden thing.

We could enforce that _newly created_ policies have a non-empty members field, but I'm not sure that this is helping much. After all, we cannot validate ldap and saml users/teams, so a user could just send `members: ["user:saml:something-silly-since-empty-members-is-forbidden"]` anyways 😉 

I'd vote for _close_ -- happy to discuss this still, though.

**Comment by susanev** [comment]
closing based on discussion.
