### ISSUE TITLE
User password match error does not work correctly

### ISSUE THREAD

**Issue by susanev** [chef/automate#1523]
## Overview
User password match error does not work correctly

## Repro steps
*  Sign in as admin
* Navigate to _Settings_ > _Users_
* Use the _Create User_ button
* Enter a password, and a matching password in the confirm password box
* Now go back to the first password box and make a change, notice that no error appears

Also:
* Click on a user to view their details page
* enter in a password
* enter the identical password with one extra character on the end
* you will see the "Passwords must match" error and the save is disabled
* add the additional character to the above password field
* error does not go away and save is not enabled

Desired: 
1) Whenever the two password fields do not match an error should be presented to the user.
2) When they match (whether the first is corrected to match the second or the reverse), the error should go away and the save button should be enabled.

**Comment by blakestier** [comment]
ALSO:

We need something similar on the password field. Right now you have two different behaviors and they should behave similarly.
Name--once the error displays then typing a new character in the field immediately hides the error (because of this method).
Password--once the error displays then the error remains until you press "Create User" again.
Should be consistent here and with other auth resources (which act like Name).
