### ISSUE TITLE
new endpoint suggestion: export node reports

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#178]
# User Story

We currently have export endpoints for both the cfgmgmt api and the compliance reporting api that return the latest report (client run or inspec scan) for all nodes present in the (filtered) nodes list.
This maps to the export buttons on the Client Runs and Compliance Reporting pages.

I've heard some requests from users that they would like to download all the reports for a single node, or at least all the reports from within a time range for a single node. It feels like we could leverage the work we've done with the current export endpoint to support this request with a minimal amount of work.

# Definition of Done

endpoint that supports exporting of all reports for a single node (respects filters, including time, profile, control ones)

# Aha link
https://chef-internal.ideas.aha.io/ideas/A2-I-37

**Comment by lancewf** [comment]
This is an interesting task. I don't see a problem with adding this for the client runs nodes.

**Comment by vjeffrey** [comment]
oooh ya, that way it matches the timeframe set out there. nice! @jonong1972 whaddya think?

**Comment by jonong1972** [comment]
@lancewf  I have a question about this. So when a user downloads - what exactly are they downloading?  assumption right now is....  if the node has 3 runs in the past 24 hours, the export file would contain a list of resources x 3?  Would this report also include the Run List and Attributes?  Or just the Resources.

**Comment by jonong1972** [comment]
Okay, just chatted with @vjeffrey . Yes. A download would be cool to have the history of one node. 

Looking at an existing downloaded CSV file from the Client Run List page, we noticed that if a client run failed it does not show the error in the CSV file.

So that leaves the question of where to put the 'download' link/button.  I need to confer with the UX team about this, since we are actively working on that side drawer component.  I would prefer to have the download button link next to the History Button on the details page, and when clicked, a modal would show asking the time frame drop down.  But I need to talk with my team first.

**Comment by vjeffrey** [comment]
it sounds like we want to break this up into two issues?
one for client runs node reports and one for compliance?

**Comment by vjeffrey** [comment]
closing in favor of #1764 and #1765
