### ISSUE TITLE
Add search filter to global projects dropdown

### ISSUE THREAD

**Issue by susanev** [chef/automate#1841]
## Overview
- add search/filter to the top of the global projects dropdown
- that will display matching project names as the user types
- the amount displayed will be limited to some fixed amount

### General Project Menu
- Triangle menu indicator at the top should be visible, it was already added but was hidden when we changed how we handle overflow (susan add link to pr)
- Change max height so unassigned + up to 10 projects are always visible
- Change width to support 2 buttons side-by-side

### Search
- If a user has access to 2 or more projects than search should be shown
- 14px space between top of menu and sides
- Placeholder text "Filter projects..."
- line separating search from buttons
- as the user types the projects list should filter
- filter should be case insensitive
- if a user closes the menu the search should be cleared

### Button Changes and Additions
- Move _Apply Changes_ button to right above project list
    - primary
- Add _Clear Selection_ button to right of _Apply Changes_ button
    - tertiary
    - Only visible when at least one project is already selected and applied

#### Clear Selection Functionality
- Clear selection should uncheck all selected projects, even if they are not visible
- On clear selection, the menu should close and the top label should update

### Project checkbox list
- change font-weight to 400
- this is the only area that should be scrollable

### More options at bottom
- Add _Create new Project_ option with same styles from user menu
    - Only display this if a user has permission to create a project
    - On action, this menu should close and the create project modal should open
- Add _Edit Projects_ option with same styles as user menu
    - Only display this if a user has access to edit at least one project
    - On action, this menu should close and the user should be navigated to the projects list page

### No search results
- display the text in italics `No projects found.  You don't have access to any projects that match your search.`

### Screenshots

![projects-filter-with-search](https://user-images.githubusercontent.com/5489125/69502666-9e472e80-0ec6-11ea-8e82-15d9369ba124.png)

![projects-filter-no-search-results](https://user-images.githubusercontent.com/5489125/69502665-9e472e80-0ec6-11ea-97fd-0ed373a1572a.png)

**Comment by msorens** [comment]
Looking great, @susanev! Some thoughts sparked by your comment "clearing a selection should not close the menu, but it should update the top label..."

So right now we have:
```
**Apply Changes**   - (a) update the top label and (b) close the dropdown.
checking/unchecking - (a) do not update the top label and (b) do not close the dropdown.
```
It sounds like you want **Clear Selection** to be this hybrid:
```
**Clear Selection** - (a) update the top label and (b) do not close the dropdown.
```

Having **Clear Selection** update the top label might be surprising because adding to a selection (checking/unchecking) does not update the top label.
Also, there is overhead: updating the top label goes hand in hand with applying the project filter to the page. Thus, if a user wants to do a two-step process--clear the current selection then pick some different projects--they have to wait for the filter to be applied twice: upon selecting **Clear Selection** then again upon selecting **Apply Changes**.

But there's more...

Consider the following scenario:
Type "C" then select project Castor. Delete the "C" and type "P", then select project Pollux. At this point, the user has only **one** checked project visible yet there are, in fact, **two** selected projects. (Or even more, if they did not start with an empty list.) Should there not be some visual indicator telling the user either a count of checked projects or the actual list of checked projects? One solution is that checking/unchecking could update the top label immediately--just like **Clear Selection**--and that will provide necessary feedback. So this suggests a change in behavior: while the dropdown is open, updates to the top label do **not** get applied to the page. Only when you select **Apply Changes** do changes get applied to the page.

Might work. But in that scenario, what happens if you close the dropdown without selecting **Apply Changes** ? Then the top label should revert to displaying what was last applied. Open the dropdown again and the top label remains showing what was last applied, because all previous unapplied changes are lost (that's current behavior), just like the previous search values will be lost (per your spec above).

Wrapping back to **Clear Selection**: with the above behavior, this no longer has overhead--it just changes the top label without affecting the display on the page. Which also means you would then have to select **Apply Changes** for it to take effect.

Quite a lot of UX to consider here, I would say. 😁

**Comment by msorens** [comment]
Under **Design Details** might want to add explicitly something to the effect: "filtering the list by typing in the search bar does not change the current selection."
That is, just because you cannot see a checked project does not mean it gets unchecked.

**Comment by SEAjamieD** [comment]
Open PR: https://github.com/chef/automate/pull/2671
