### ISSUE TITLE
resolve security vulnerabilities in chef-ui-library

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#186]
# User Story

The current list of vulnerabilities can be found [here](https://github.com/chef/automate/network/alerts)

It looks like these are all dependencies of the chef-ui-library.  Let's see what we can do to resolve these.

# Definition of Done
No more security alerts for chef-ui-library.

**Comment by scottopherson** [comment]
Dumping some notes here when I looked at the vulnerabilities earlier this week. All vulnerable packages, except lodash, are not directly depended on by us so some may be a little tricky to fix.

---

merge@1.12.0 -> merge@>=1.12.1

```
├─┬ jest-cli@23.6.0
│ └─┬ jest-haste-map@23.6.0
│   └─┬ sane@2.5.2
│     └─┬ exec-sh@0.2.2
│       └── merge@1.2.0
└─┬ sass-lint@1.12.1
  └── merge@1.2.0
```

Latest sass-lint, 1.13.0, uses merge@1.12.1 but 1.13.0 isn't published to npm for some reason.
Latest jest-cli, 24.7.1, uses merge@1.12.1 but the changelog between it and 23.6.0 has a lot of breaking changes we'd need to watch out for. Will likely want manually override instead since we only need a minor version bump.

---

semver@2.3.2 -> semver@>=4.3.2

```
├─┬ @stencil/core@0.17.0
│ └─┬ chokidar@2.0.3
│   └─┬ fsevents@1.1.3
│     └─┬ node-pre-gyp@0.6.39
│       └── semver@5.3.0
├─┬ @stencil/sass@0.1.1
│ └─┬ node-sass@4.9.3
│   └─┬ node-gyp@3.8.0
│     └── semver@5.3.0
├─┬ jest-cli@23.6.0
│ ├─┬ istanbul-lib-instrument@1.10.2
│ │ └── semver@5.6.0
│ ├─┬ jest-haste-map@23.6.0
│ │ └─┬ sane@2.5.2
│ │   └─┬ fsevents@1.2.4
│ │     └─┬ node-pre-gyp@0.10.0
│ │       └── semver@5.5.0
│ ├─┬ jest-snapshot@23.6.0
│ │ └── semver@5.6.0
│ └─┬ node-notifier@5.3.0
│   └── semver@5.6.0
├─┬ node-sass@4.10.0
│ ├─┬ meow@3.7.0
│ │ └─┬ normalize-package-data@2.4.0
│ │   └── semver@2.3.2
│ └─┬ node-gyp@3.8.0
│   └── semver@5.3.0
└─┬ tslint@5.12.1
  └── semver@5.6.0
```

semver 5.6.0, 5.5.0, 5.3.0, 2.3.2 are being pulled in. Upstream deps of node-sass@4.10.0 is pulling in the vulnerable semver@2.3.2.

---

atob@2.0.3 -> atob@>=2.1.0

```
└─┬ @stencil/core@0.17.0
  └─┬ chokidar@2.0.3
    └─┬ braces@2.3.1
      └─┬ snapdragon@0.8.2
        └─┬ source-map-resolve@0.5.1
          └── atob@2.0.3
```

Far upstream but cited vulnerability only applies to Node 4.x and below. We're currently on Node 5.6.x.

---

extend@3.0.1 -> extend@>=3.0.2

```
├─┬ @stencil/core@0.17.0
│ ├─┬ chokidar@2.0.3
│ │ └─┬ fsevents@1.1.3
│ │   └─┬ node-pre-gyp@0.6.39
│ │     └─┬ request@2.81.0
│ │       └── extend@3.0.1
│ └─┬ jsdom@11.11.0
│   └─┬ request@2.88.0
│     └── extend@3.0.2
├─┬ @stencil/sass@0.1.1
│ └─┬ node-sass@4.9.3
│   └─┬ request@2.87.0
│     └── extend@3.0.1
├─┬ jest-cli@23.6.0
│ └─┬ jest-environment-jsdom@23.4.0
│   └─┬ jsdom@11.12.0
│     └─┬ request@2.88.0
│       └── extend@3.0.2
└─┬ node-sass@4.10.0
  ├─┬ node-gyp@3.8.0
  │ └─┬ request@2.88.0
  │   └── extend@3.0.2
  └─┬ request@2.88.0
    └── extend@3.0.2
```

Found numerous times upstream but only needs a minor bump.

---

randomatic@1.1.7 -> randomatic@>=3.0.0

```
└─┬ jest-cli@23.6.0
  └─┬ micromatch@2.3.11
    └─┬ braces@1.8.5
      └─┬ expand-range@1.8.2
        └─┬ fill-range@2.2.3
          └── randomatic@1.1.7
```

Requires quite a large version bump but it's a random number generator so shouldn't be too problematic...

---

lodash@4.17.5 -> lodash@>=4.17.11

```
├─┬ @stencil/core@0.17.0
│ └─┬ jsdom@11.11.0
│   └─┬ request-promise-native@1.0.5
│     └─┬ request-promise-core@1.1.1
│       └── lodash@4.17.5
├─┬ jest-cli@23.6.0
│ ├─┬ istanbul-api@1.3.7
│ │ └─┬ async@2.6.1
│ │   └── lodash@4.17.11
│ ├─┬ istanbul-lib-instrument@1.10.2
│ │ ├─┬ babel-generator@6.26.1
│ │ │ └── lodash@4.17.5
│ │ ├─┬ babel-template@6.26.0
│ │ │ └── lodash@4.17.5
│ │ ├─┬ babel-traverse@6.26.0
│ │ │ └── lodash@4.17.5
│ │ └─┬ babel-types@6.26.0
│ │   └── lodash@4.17.5
│ └─┬ jest-config@23.6.0
│   └─┬ babel-core@6.26.3
│     ├─┬ babel-register@6.26.0
│     │ └── lodash@4.17.5
│     └── lodash@4.17.5
├── lodash@4.17.5
├─┬ node-sass@4.10.0
│ └─┬ sass-graph@2.2.4
│   └── lodash@4.17.5
├─┬ redux@3.7.2
│ └── lodash@4.17.5
├─┬ sass-lint@1.12.1
│ ├─┬ eslint@2.13.1
│ │ ├─┬ inquirer@0.12.0
│ │ │ └── lodash@4.17.5
│ │ ├── lodash@4.17.5
│ │ └─┬ table@3.8.3
│ │   └── lodash@4.17.5
│ └─┬ globule@1.2.0
│   └── lodash@4.17.5
└─┬ typedoc@0.14.2
  └── lodash@4.17.11
```

Found numerous times upstream and is the only pkg we depend on directly. Only needs a minor version bump, should be low drama.

---
