### ISSUE TITLE
close-x on member expression navigates incorrectly to list page

### ISSUE THREAD

**Issue by susanev** [chef/automate#1934]
## Overview
If you use the close-x button on the member expression modal it navigates you to the list page, but it should close the modal and leave you on the add members page.

## Repro steps
* Sign in as admin
* Navigate to _Settings_ > _Policies_
* Navigate to any policy and then the _Members_ tab of that policy
* Use the _Add Members_ button followed by the _Add Member Expression_ button
* Use the close-x on the member expression modal and notice that it navigates you back to the list page

### Expected behaviour
* It should close the modal and leave you on the add members page

**Comment by SEAjamieD** [comment]
@tarablack01 / @scott / @Shadae -

The issue here is we have two stencil components using event emitters with the same name, and when the inner components fires the event emitter `close`, both the components are reacting to it.

structure looks like this:
```
<chef-page (close="closePage")>
    <chef-modal (close)="closeModal()">
    </chef-modal>
</chef-page>
```

Any preference on best route to change this?  Thinking i'll just rename `chef-modal`'s emitter to be `closeModal` and then update all the components using modals.
