### ISSUE TITLE
Run History shows the local time but with a UTC label

### ISSUE THREAD

**Issue by brywilliamsCF** [chef/automate#1938]
## Describe the bug
When viewing Client Runs the time is listed inaccurately on the page header, the Run Duration field, and the Run History tab.  It shows the local time but with a UTC label.

## To Reproduce
View the client run times listed for a server and compare them with the times in the chef-client.log on the server or the times listed in the Chef Manage interface.

## Expected behavior
The time should display as ~either the local time, the local time with a timezone label, or in~ UTC time with a UTC label.

## Screenshots
![image](https://user-images.githubusercontent.com/44782158/67299366-314d0d00-f4b2-11e9-8c74-d51c080d08a3.png)
![image](https://user-images.githubusercontent.com/44782158/67299013-b97ee280-f4b1-11e9-9f6d-fa2e8c62d4ca.png)

## Versions (please complete the following information):
- OS: CentOS 7
- Chrome
- Automate Build 20191001203421

## Additional context
I believe this started in Automate Build 20191007115919.

**Comment by SEAjamieD** [comment]
i'll pick this up right now

**Comment by SEAjamieD** [comment]
@jonong1972 @brywilliamsCF - should we be displaying all times in UTC format now?

I noticed the initial datetime pipe we are using is formatting in local time, which is why we were seeing local time.  a quick addition of `.utc()` in the datetime pipe will render all the times in UTC format (it wont affect the display...i.e. Wed, 03 Jul 2019 17:08:53 UTC) just the actual local vs. UTC.

ref: https://momentjs.com/docs/#/parsing/utc/
chef datetime pipe: https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pipes/datetime.pipe.ts

**Comment by jonong1972** [comment]
@SEAjamieD Yes!  that would be great
