### ISSUE TITLE
Address differences between effortless nodes and client run and compliance nodes

### ISSUE THREAD

**Issue by susanev** [chef/automate#1946]
## Updated Approach
Document the differences and then revisit after GA.

### Overview
Effortless nodes will only come in with two attributes _Environment_ and _Policy Name_ so we will need an additional ingest rule type of _Chef Solo Node_ with those two attributes.

### Design Details
- Change the `Node` ingest rule type to `Chef Server Node`
- Add a new ingest rule type of `Chef Solo Node`
    - it should have two possible attributes `Environment` and `Policy Name`
- These changes should be reflected in both the front-end and back-end

### Documentation Updates
- Anywhere we mention ingest rule types or attribute options should be changed to include _Chef Solo Node_.
- Anywhere we mention the `Node` ingest rule type it should be changed to `Chef Server Node`

**Comment by vjeffrey** [comment]
do we currently have users set diff ingest rules for compliance nodes and client run nodes, or is that all one: « ingested nodes »?

**Comment by susanev** [comment]
its one type _Node_ for compliance and client run nodes

**Comment by susanev** [comment]
an alternative solution would be to not have a new type and communicate to sers in a different way that effortless nodes can only use two of the attributes listed.

**Comment by vjeffrey** [comment]
i was bouncing between the two ideas in my head. if a user specified a field like chef tags for a node using effortless, the rules wouldn’t match the node, which would leave the user in a pretty confused state, so new option sounds good to me!

**Comment by lancewf** [comment]
Below are some notes about this task
- I think this task needs a spike subtask. 
-- Run effortless to get sample reports
- Would this match compliance effortless nodes?
- Would the Chef Solo Node rules only tag Chef Solo nodes?
-- If yes, how do we tell the difference between a Chef Solo node and Chef Server node in the ingest-service? 
--- If the “SourceFqdn” field of the CCR is “localhost” then the node is from Chef Solo. 
- The ingestion project tagging and project update will have to be changed for ingest-service, compliance-service, and nodemanager. 
- This might be confusing to users because we do not currently have a way to view only Chef Solo Nodes. 
- One solution is to not have a different type but have the user create a project rule with a condition that matches “Chef Server” = “localhost” then add the other condition to only match Chef Solo nodes
- We should ensure that “Chef Tags” are not part of the Effortless report.

**Comment by susanev** [comment]
I think the intent is just to filter what is possible for the effortless nodes, but honestly don't totally know enough to fully understand ur comment.
