### ISSUE TITLE
Project Deletion: Ingested Resources

### ISSUE THREAD

**Issue by susanev** [chef/automate#2016]
## Overview

As a user of IAM and Projects, when I delete a project, I expect that the project I deleted will be removed from all resources. Currently, when I delete a project, a reference to that project remains on ingested resources, which causes those resources to **NOT** appear in the `(unassigned)` filter like I would expect them to.

## Design Details

Ideally, we can remove those project ids from ingested resources without needing to do a project update.

**Comment by sdelano** [comment]
I was under the impression that project deletion triggered removal of the project from all resources, including the ones that ran through ingestion. If that's the case, do we need this?

**Comment by susanev** [comment]
It only triggers removal from non-infected resources

**Comment by sdelano** [comment]
Implementation notes from discussion today:

```
- when a user deletes a project via the API or the UI:
  - there's a flag in the projects table that says the project is
    marked for delete
    - if marked, the project won't show up via the APIs
    - doesn't show up in GET APIs
    - maybe we do need a way to show it in the API so they know they
      what changed
  - there's NO API right now for determining whether we need to apply rules
    - we could implement this if we want the banner eventually
  - on 'Update Projects'
    - insert the project into the graveyard
    - delete the project first
      - disappears from the table
      - cascade delete of all the rules and other stuff
    - need to ensure that the listProjectRules API doesn't have the project
    - move the staged rules
      - is there an edge case here?
    - cereal jobs
      - updating the compliance and ingest domains
      - deletes project from teams and tokens
      - remove project from the graveyard after all the cereal things
        are done
      - note: calculation of done % is going to need to be updated
```

**Comment by susanev** [comment]
i guess the other thing we discussed at some point was to prevent the deletion of a project until it had zero ingest rules and was up-to-date... that may be another approach to consider.

**Comment by sdelano** [comment]
*NOTE*: The implementation detail discussion above relates to the previous iteration of this card that framed the issue around the 'Update Projects' button instead of the expectations of the user. Please disregard the implementation above and let's take a look at this again with a fresh approach.

**Comment by sdelano** [comment]
Notes from sprint planning:
- need to delete the project from postgres and all the rules associated with it
- have a job that goes through and deletes the project references from the ES data
  - can be run via a painless script in ES
  - should be run via a cereal job by the services responsible for the data, e.g. ingest service, compliance, config mgmt
  
Failure cases and race conditions:
- what happens if project update is happening at the same time as deletion?


Painless update looks **something like**:

```
cat <<EOF | 
{
"script": {
  "source":"ctx._source.projects.remove(project)",
  "lang":"painless",
  "params": {"project":"avengers"}
  }
}
EOF                                                                                                              
curl -H'content-type:application/json' -XPOST http://localhost:10141/node-state/_update_by_query&q=*:* -d @- | less
```

**Comment by blakestier** [comment]
Update on implementation options after some discussion/exploration/work:

Closer look at options after spiking/working/discussing:

1. Just don’t allow users to delete a project in GA 
      _Work involved:_ 
- Remove control menu/delete from UI
- Return message from API “can’t do this yet” (or remove from api? :shrug:

2. Use the project update (button)  
    **UX pro**: project change is consistent with other ingested resource changes
    **UX con:** person has to wait for the possible long duration of an update for delete to take effect

	**ENG pros:**

- System is mostly in place
- Means avoiding possible collisions/race conditions around a delete because one “system” is handling it all
(If a user deletes a project and another updates that project, we think we’re ok, but if a user updates a project and then another deletes it, we’re less confident. )
(We could additionally block deletes during updates, though that’s part of the “rebuilding the same thing” concern)
- We don’t add a lot of extra code to manage/track in an already complex system
- We don’t have to build another version of ProjectUpdate (similarities abounded when we realized we needed to account for lots of the same concerns, such as a system crashing/race conditions)
- Opportunities to optimize, since if deletes/updates are all handled in ProjectUpdater, we can avoid updating a thing we’re deleting and can batch requests

		
	**ENG cons/work involved:**
_On delete of a project, we’d need to:_
- Push its rules into the staged rules table (marked for delete). This is how we currently determine whether a rule needs an update.
			OR
- Create an API which checks for deleted projects as part of determining a need for a project update.

- Modify the list API to only return projects not marked for deletion
- Modify projects db to have a `deleted` bool field
- Modify the project delete functionality to only mark a project deleted
- Ensure that the project was deleted on project update

3. Use the ProjectPurger to remove the project tag from ingested resources as well as IAM resources

**Pros:** faster than a long running project update
**Cons:** 
- not *much* faster
- requires duplication of project update work
- lots of redundancy across services
- potential race conditions around multiple deletes

4. Require user to delete a project’s rules and “Update Projects” *before* they can delete the project

**Pros:** 
- User has full understanding of the impact of project deletion/rule removal
- Pretty low effort Engwise: return API error if attempting to delete project with rules. UI messaging w/ instructions.
			
**Cons:** 
- User *might* have to wait a long time for rules to be applied and then has to remember to go _back_ to delete project
