### ISSUE TITLE
SSLify or run builder services on localhost

### ISSUE THREAD

**Issue by jaym** [chef/automate#2066]
The builder services either need to use the SSL certs we provide them or we can just start running things on localhost and stop caring.
If we do want to use SSL everywhere:
- we need to modify the api-proxy nginx template to use them
- modify the builder-api source to allow us to configure ssl
- rebuild memcached to support

**Comment by sdelano** [comment]
Sprint Planning Notes:
- *most* of the services inside of automate use SSL to communicate with each other
- this is the standard we've set so far
  - TODO: add notes on why this is the standard and whether it should be
- right now the depot services listen unauthenticated on all interfaces
  - the goal of this work is for that to not be the case
- option 1: all services use mTLS for authentication between services
  1. we had the vision that different services would be running on different machines and we'd need to be able to secure those connections
    - that hasn't necessarily played out
  2. we have played with using mTLS for authz
    - not clear how useful this has been
  3. something else
- option 2: all services only listen for connections on localhost
- bldr services
  - automate-bldr-api
  - automate-bldr-proxy
  - automate-bldr-memcached
- list of things needed
  - [ ] talk to other services via mTLS
  - [ ] bldr api doesn't support listening on mTLS
  - [ ] can build memcached w SSL support
    - not clear on mTLS implementations past that
- because every service still needs to talk to the backends via mTLS we still need to do the work of setting up the certs and the CA for them
- just listening on localhost is not as small of a task as we think it is
  - other things are calling back on the IP address

**Comment by sdelano** [comment]
accidentally closed

**Comment by stevendanna** [comment]
If we need Automate Builder to support FIPS we are going to need to patch memcache and/or not use TLS on it.
