### ISSUE TITLE
EAS services sidebar resets when you filter by a status with 0 services

### ISSUE THREAD

**Issue by kmacgugan** [chef/automate#2073]
## Describe the bug
Filtering by a status with 0 services in the service sidebar reset the applications page.

## To Reproduce
On the applications tab, when you click on a services status filter for any service group that has 0 services, then the UI will navigate back to the first service group in the list and reset the sidebar status filter to 'total'. 
It is easiest to see this on a service group that is not first in the table.

## Expected behavior
We would remain on the service group we were previously on, and we would show 0 results in the sidebar. 

## Versions (please complete the following information):
- OS: [e.g. rhel6]
- Automate Build Number [e.g. 20190701222009]

**Comment by vjeffrey** [comment]
@kmacgugan is this a backend or front end issue?

**Comment by vjeffrey** [comment]
ui!

**Comment by danielsdeleo** [comment]
I didn't find the exact cause but I did get a little more context on this one; from the browser dev tools you can see that the UI makes the correct API call and gets a response like 

```
    "group": "nginx.default",
    "services": [],
    "services_health_counts": {
        "total": 40,
        "ok": 0,
        "warning": 0,
        "critical": 40,
        "unknown": 0,
        "disconnected": 40
    }
}
```
but after that it then loads the services for whichever service group is first on the page and shows that.

**Comment by danielsdeleo** [comment]
So there is some code that explicitly makes this happen: https://github.com/chef/automate/blob/bf6c925f4dc866f47b234fd503529563456cdfef/components/automate-ui/src/app/pages/service-groups/service-groups.component.ts#L236-L255 I'll need to dig in to see if this got implemented due to a misunderstanding of requirements or if it serves some technical purpose like avoiding some buggy condition.
