### ISSUE TITLE
Find Nested Subs and Sub Missing `takeUntil(this.isDestroyed)`

### ISSUE THREAD

**Issue by sdelano** [chef/automate#2162]
We merged a bunch of PRs to get rid of leaky subscriptions. We want to do one final pass of all auth UI pages to look for:

1) Nested Subscriptions:

```
 this.store.select(someStuff).subscribe((state) => {
         ...
        this.store.select(moreStuff).subscribe((otherState) => {
```

Instead use `combineLatest` with `filter` to ensure that everything is fetched before processing data.

2) Every subscription should have `takeUntil(this.isDestroyed)` (or equivalent that completes the Observable) so they get shut down when the component unloads.

**Comment by msorens** [comment]
_This issue is an investigation. The results of the investigation will probably generate more issues for the parent epic._

Though we still have 3 open PRs that may affect the results for the better, I wanted to get a picture of how big the scope of this issue is, so I merged those 3 PRs then did an audit of all auth pages. The results are in the spreadsheet below.

### Legend

> Green -> OK as is
> Red -> needs updating (either add a `takeUntil`, or unnest subscriptions, depending on which column it is in)
> Yellow -> `takeUntil` is applied... sometimes; we probably want it to apply all the time, but a point worth discussing.

### Summary of the Spreadsheet Data

- 6 subscription missing `takeUntil`
- 6 subscriptions nested
- 16 subscriptions have `takeUntil` conditionally

https://docs.google.com/spreadsheets/d/17n8G693ChnCjz9pfie5Gmj6q6hfs-0v-T7R557tYgzU/edit?usp=sharing
