### ISSUE TITLE
[Applications UX] Display detailed release info when there are multiple releases available for a service group in the table

### ISSUE THREAD

**Issue by apriofrost** [chef/automate#2198]
## Problem
On the service group page, when there are multiple releases of a package available for a service group, in the "release" column, there is only a count showing the number of releases. It's hard to understand what these releases are. Users have to go through the side panel and figure out the answer by scrolling through all the instance cards, read and compare the package identifier info within the card.
In addition, the situation where multiple releases exist for a service group is not uncommon for the users who are seeing this problem. They use it primarily to manage their point-of-sale software across thousands of stores. Their software updates do not roll out all at once. Usually, the rollout process starts with 1, 10, 100,1000, and then the rest. Therefore, it is important for them to know what are the different releases they currently have for the specific app in an environment (channel).

![image](https://user-images.githubusercontent.com/9401459/68797740-fb5efc80-0609-11ea-99df-16b3244e20c0.png)

## Ideal User Experience
When users see that there are multiple releases exist for a service group, provide them with:
- the count number of how many releases there are in total
- the identifiers for these specific releases (`version`/`build-timestamp`)
- the ability to filter and sort through the service instances in the group by releases

### Designer Note
@apriofrost needs to think more about what the solutions could be to provide this experience. Any ideas or feedback are welcome in the comments!

**Comment by ericcalabretta** [comment]
@apriofrost I think this is a great observation. Depending on the application and the speed that organization moves these releases may take significant time. You may be in a release for a few days or weeks, so being able to show what's on release A vs B at scale would be very helpful. 

Maybe a `release group` filter in addition to app or service group. If users don't leverage Channel + `--strategy at-once` It's hard to catch where things are in the release process by the primitives we have at the moment. Another thing like Chef Infra/Jenkins/Terraform could be responsible for the specific Habitat package number rather than upgrade strategies.

**Comment by susanev** [comment]
this work has been deprioritized.
