### ISSUE TITLE
Filter part of error message when access to only one project is confusing

### ISSUE THREAD

**Issue by blakestier** [chef/automate#2217]
## Current Behavior

As an Automate User with a project selected in the global project dropdown, I attempt to take a non-permitted action (delete user, edit user) and see an error message containing the text "filtered by projects []".

## Desired Behavior

As an Automate User with a project selected in the global project dropdown, I attempt to take a non-permitted action (delete user, edit user) and see an error message containing the text "filtered by projects ["project-id"].

![ProjectFilterEmptyOnError.png](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/27c33945-bc88-4f48-b1aa-2dffb668ec8d)

**Comment by sdelano** [comment]
@susanev notcied that this happens when the `zeta` project is the only project this use has available: e.g. there's no dropdown to select another project.

Given that, my assumption is that we're not actually applying the project filter to the API requests and that the UI is trying to be smart about what the user can see. Could you check:

1. that the projects filter header is actually applied to the API requests
2. that this also occurs when there is more than one project available to the user

**Comment by blakestier** [comment]
1. The project is not sent in the header if the user only has access to one project.
2. This does not occur when there is more than one project available.

Given that the user only has access to the one project, their actions *are* getting correctly authorization.

**Comment by sdelano** [comment]
Thanks @blakestier! So the extent of this issue is that the error message is reflecting the state of the world: "user can't take this action and they have no project filters applied" and because the UI is trying to be helpful by showing "you only have access to one project" it causes confusion about what is really going on. Correct?

**Comment by blakestier** [comment]
Yes, something like that. The Global Filter *appears* populated (by the single permitted project) so it's surprising for the filter to be `[]` in the error message.

We could simply drop that part of the error message when the filter is empty (unless that makes the msg less helpful?)

**Comment by susanev** [comment]
so, in that case, they don't actually have any filters applied.
i dont think that part of the message is useful in the access to a single project case, and i also want to customize it to better communicate a filter isnt applied, instead of saying empty array. im gonna take a bit to think about it though.

**Comment by susanev** [comment]
this work has been deprioritized.
