### ISSUE TITLE
Ingest Rule ID Conflicts

### ISSUE THREAD

**Issue by susanev** [chef/automate#2372]
## Overview

As a user of IAM Projects and Ingest Rules in Chef Automate, I find it mildly annoying that I must create ingest rules with a globally unique (within my Automate instance) ID. It would make my life easier, and potentially more secure, if the names and IDs of ingest rules were only required to be unique to the projects themselves as opposed to unique across all projects.

## Example

I'd like to create two projects that ingest nodes based on their Chef organizations, I'll call them `x-men` and `avengers`. Once I've created the projects, I'll need to create the ingest rules to handle this mapping, which requires me to provide an ID for the rule. Since I'm just mapping based on a Chef organization, I decide to use the ID `org`. When I try to do the same thing for the second project, I get an error notifying me of a conflict of the rule ID. Now I must adopt my own ID strategy for rules that hopefully other users of Chef Automate at my company should also follow:

* rule IDs could follow the convention `$projectName-org`
* rule IDs could follow the convention `org-$orgName`
* any other conventions I might decide are appropriate.

## Impact

The above scenario is frustrating because:

1. If somebody in my Company doesn't adhere to the naming convention, then I'm left with no choice but to break the convention myself to make progress. 
1. The rule URLs are namespaced by project, so I assume that they're unique per project, e.g.
   * `projects/avengers/rules/org`
   * `projects/x-men/rules/org`
   
   The above URLs are both unique, so even though they have the same ID then I'd expect the resources to be unique as well
1. Users in other projects could:
   * exhaust the IDs for rules that I'd like to use
   * discover the existence of rules that they might not have access to by trying to create ones of the same ID

## Expected Behavior

I expect that if there are no rules in my current project with a certain ID then I can create a rule with that ID. I also expect that users in other projects will not be able to discover the existence of my rules with a brute force attack of rule creation.

**Comment by susanev** [comment]
needs team discussion

**Comment by blakestier** [comment]
Is he wed to the defining the _name_ or the _id_? Because we could 1) Get rid of definable rule ids (like statements) or 2) autogenerate unique ids on conflict.

Names don't really need to be unique-- he's hitting this bc we build the ID off of the name.

**Comment by sdelano** [comment]
Oops @blakestier sorry about that. Fixed with `s/name/ID`

**Comment by sdelano** [comment]
Notes from today's discussion between myself @susanev @blakestier @bcmdarroch @tylercloke and @lancewf 

## Historical Context
At one point during the development of projects and mapping rules, the rules API was a globally referenced API, e.g. `iam/v2/rules` instead of `iam/v2/projects/pid/rules`, so the global uniqueness constraint is most definitely a carry-over from that time.

Since we didn't (and currently don't) have any plans to make rules reference-able outside of the context of a single project, it made sense to make the rules API a subset of the projects API. When we did so, we did not re-evaluate the uniqueness constraints, which results in the potentially confusing or annoying behavior that we see here.

## Decisions
* **Is this a valid issue that we're concerned about?** Yes it is. Unless we'd like to be able to share or reference rules between projects, then it doesn't make sense for the uniqueness constraint on the ID to be global.
   * In his feedback which resulted in this issue, Matt Ray (@mattray) had mentioned the desire to be able to share rules between projects. We'd like to get more information on this from him before we address this issue.
* **Does this need to be solved before GA?** No. This is currently a minor annoyance and should be relatively easy to address.
* **Would solving this before GA be easier?** No. The change we have in mind would be loosening the uniqueness constraints on rule IDs. Going in the reverse direction, tightening constraints (e.g. undoing this) would potentially be a more complex and carefully engineered migration, so we want to make sure that we've taken into account any future use cases before proceeding.

## UUIDs
We discussed but decided against the idea of treating rules in the same way we do policy statements. Statements have no names and get auto-generated UUIDs. However, statements can only be updated as part of a policy update, while rules can be updated individually. So we would like to keep a human-readable unique ID for project rules.

## Action Items
* [ ] Follow up with @mattray on the use cases for sharing rules between projects so we can take that into account in our approach here.
* [ ] Schedule this work for post-GA

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
