### ISSUE TITLE
some inputs have lost their styles

### ISSUE THREAD

**Issue by susanev** [chef/automate#2380]
## Overview
The profile search input, along with some of the inputs on node integrations seem to have lost there styles.

### Current
![profile-search-current](https://user-images.githubusercontent.com/5489125/69762773-1bb9ab80-1120-11ea-9b5c-f73e4e1ccf59.png)

### Expected
![profile-serach-expected](https://user-images.githubusercontent.com/5489125/69762776-1e1c0580-1120-11ea-88bc-70b9c9fddc3b.png)

**Comment by vjeffrey** [comment]
this is also on the node integrations create screens:
<img width="893" alt="Screen Shot 2019-12-02 at 09 41 22" src="https://user-images.githubusercontent.com/10341541/69977399-f645ec80-14e7-11ea-87e2-ec50e0a6139c.png">

**Comment by SEAjamieD** [comment]
I'll pick this up since I just did all the chef-input stuff.  Should be a quick fix

**Comment by SEAjamieD** [comment]
@chef/ui-team  - Sourcing opinions here...

What's going on is that our inputs are now using the #chefInput directive for styling purposes.  with our current setup, this requires `chef-form-field` to wrap the input.  We are seeing inconsistency because this works if chef-form-field is simply present on the page somewhere.

My thought is that we have 2 solid options.
1) require that every input is wrapped in `chef-form-field`.
2) move `.chef-input` class styling into global scope.

My opinion is that `.chef-input` class should be moved into the global scope, as we want these all to have a consistent styling unless specifically overwritten in their local CSS.  Anyone have strong opinions?

**Comment by Shadae** [comment]
Let's try your opinion and see how it goes. We don't want to bloat global scope but this might be a good instance to insert some global styling. Ping me when the branch is up so I can give it a look.
