### ISSUE TITLE
prevent project deletion until zero ingest rules and up-to-date

### ISSUE THREAD

**Issue by susanev** [chef/automate#2441]
## Overview
Prevent project deletion until zero ingest rules and up-to-date.

### ui
When a user tries to delete a project that has more than zero ingest rules or is not up-to-date display text in the modal indicating they need to delete their ingest rules and update projects before they can delete.

### api
Respond with an error that says the user needs to delete their ingest rules and update projects before they can delete.

### technical notes
for a delete operation to complete, the project must have no applied rules and no staged rules

**Comment by msorens** [comment]
Some design thoughts:

1. Simultaneous project deletions
- OK for simultaneous deletions for *different* projects
- Cereal is configured to apply mutex for multiple deletions on the *same* project.

2. Attempt to add rules simultaneous with a project deletion
- Modify the project purger so that it initiates a DB transaction to lock the rules table(s) then, does its purging to prevent race conditions. If it cannot get a lock--meaning someone is in the process of updating the rules table, then the cereal workflow should abort.

**Comment by lancewf** [comment]
The case above "For the Attempt to add rules simultaneous with a project deletion". This is the case where we have two users modifying the same project at the same time. One user "A" is deleting a project and the other user "B" is adding a rule to the same project. We found that this will not be a large concern because either user "B" will get an error that the project was deleted when they add the rule or no error but the project will be removed the next time they refresh the page. In the second case, if user "B" applies rules the project deleted will not be recreated. User "B" will have some confusion, but this is expected because user "A" deleted the project.
