### ISSUE TITLE
add docs for compliance report limit size

### ISSUE THREAD

**Issue by susanev** [chef/automate#2534]
## Overview

There is a 4MB limit on the compliance report, lets add this information to the docs.. specifically prolly somewhere in [troubleshooting](https://automate.chef.io/docs/troubleshooting/) and the [compliance reports](https://automate.chef.io/docs/reports/) page.

## Related Resources
[Community submitted issue
](https://github.com/chef/automate/issues/1417)

**Comment by vjeffrey** [comment]
tricks to make a larger than 4mb report smaller, so that it can be ingested:

audit cookbook 9.4.0+ supports some attribute options that can be used to trim a report to its smallest size when combined with latest automate; see https://github.com/chef-cookbooks/audit/pull/427/files and https://github.com/chef/automate/pull/3780

**Comment by mjingle** [comment]
https://github.com/chef/automate/pull/4250 addresses documentation on _Reports_. Another PR will follow for troubleshooting details.

**Comment by mjingle** [comment]
https://github.com/chef/automate/pull/4364 addresses documentation for troubleshooting.
