### ISSUE TITLE
Compliance reports page does not work as expected when filtering by control

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#2590]
## Describe the bug
There are kinda two bugs at play here.
- filtering by a control does not filter the profiles list down to only the profiles that include that control. instead, filtering by a control (without profile filter) simply returns all the profiles executed by nodes that executed the filter control. 
<img width="1091" alt="Screen Shot 2019-12-30 at 14 12 07" src="https://user-images.githubusercontent.com/10341541/71600923-6ad37180-2b0e-11ea-96cc-711635c42680.png">

- since it is possible to then click into the details view of a profile that cannot match the applied control filter, we get a service crash:
<img width="1241" alt="Screen Shot 2019-12-30 at 13 57 00" src="https://user-images.githubusercontent.com/10341541/71600959-95252f00-2b0e-11ea-84bb-821c35e9fdbc.png">

## To Reproduce
- load some compliance scans
- filter by only a control
- note the profiles list includes profiles that do not include that control
- click into the details of one of the profiles that does not include the control

## Expected behavior
Only show me the profiles that include the control I asked to filter on.

## Versions (please complete the following information):
- Automate Build Number 20191223220227

**Comment by phiggins** [comment]
The crash bug appears to have been fixed in https://github.com/chef/automate/pull/2549. That PR was merged a few days after the build number mentioned above was released.

There are two interrelated bugs left over:
* The profiles search results list profiles that do not contain the control.
* The counts of profiles and controls do not reflect the actual counts of matching controls (ie, since we're searching for one control id, exactly one profile and one control should be the result).

The cause of this appears to be that the UI is only sending a control id and the backend cannot search only by control, it expects a profile id and control id in order to do searching by control.

**Comment by vjeffrey** [comment]
i'm glad the service crash is fixed!

for the first remaining issue, "The profiles search results list profiles that do not contain the control", if it's not really possible to do this without a lot of work, let's work with ux on how to tell the user that the filter isn't being applied to that list

for the second one,  "counts of profiles and controls do not reflect the actual counts of matching controls", i wonder if that's related to https://app.zenhub.com/workspaces/automate-future-work-5dc5b0b4f3f3b50001ac1009/issues/chef/automate/1835#issuecomment-540703594 , and falls into that same bucket of "this just won't work"

**Comment by phiggins** [comment]
I added some failing tests with the expected behavior in #2744. After talking with @rickmarry, it does not seem this will be fixable in a straightforward way because our data is not set up to be searchable with a control without searching in the context of a profile that contains the control.

**Comment by vjeffrey** [comment]
thank you @phiggins -- i'm going to go ahead and close this and open an issue to have ux figure out a way to communicate to the user that the control filter does not filter the list of profiles down!
