### ISSUE TITLE
Conflicting / incorrect API call documentation to delete a node

### ISSUE THREAD

**Issue by mwronka-chef** [chef/automate#2664]
## Describe the bug
There seems to be more than one way to delete nodes via API calls from A2:

**ReDoc:**
https://automate.chef.io/docs/api/#operation/DeleteMixin56
**Automate 2 Docs:**
https://automate.chef.io/docs/client-runs/#request-for-deleting-a-node-using-the-node-id

API call from the ReDoc returns 200 response, but the node is still visible in A2 and continues to be visible for days after the API call is executed.
API call from A2 Docs works as expected and is reflected in the GUI right away as well.

## Expected behavior
Does ReDoc document the expected/correct way of deleting a node?
Are the other API calls under ReDoc expected to work?
Should ReDoc be externally visible to end users, or is it documenting some internal APIs?

## Versions (please complete the following information):
- Client OS: Windows
- API calls from PowerShell script
- Automate 20191211163405

## Additional context
Creating this issue out of interaction with customer who was looking for documentation around deleting nodes listed in A2 using API calls.
The first way they found was ReDoc and after that API call not working, resulted in Support ticket
Only after the alternative method from A2 Docs (nodedelete) was identified, customer was able to confirm success.

**Comment by susanev** [comment]
@mwrock i think the api docs link is for compliance nodes similar to this one in the automate docs https://automate.chef.io/docs/nodes/, @vjeffrey can confirm and we prolly need to improve the left nav a bit in the api docs to make that more clear.

i dont believe we have documented the ingest api yet.. again @vjeffrey or @kagarmoe can confirm.

**Comment by vjeffrey** [comment]
hi @mwronka-chef -- as @susanev noted, we have not yet documented the api calls for the ingest service, which is why you cannot find https://automate.chef.io/docs/client-runs/#request-for-deleting-a-node-using-the-node-id in the api docs. The api docs are a work in progress, we are slowly working towards getting them all documented but it takes time.

the `api/v0/nodes` endpoints you found in the api docs is the endpoint that will be serving the "one node view" (https://github.com/chef/automate/issues/911). Here we store metadata about all ingested and manually added nodes. This node store has a postgres backend (unlike ingest, which uses elasticsearch). 

We have an issue open to ensure that when a node is deleted from ingest service, that action is propagated to the postgres node store; that work should happen in the next month (https://github.com/chef/automate/issues/616).

If you have any suggestions for how to make this more clear, please let us know!

**Comment by susanev** [comment]
going to close this, please let us know if we can help in any way.
