### ISSUE TITLE
connectivity error for node is hard to read when long

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#285]
# User Story

As shown in this screenshot, if an error is long, we do not do any word wrapping, leaving the user with the burden of sliding the bar all the way across to read. This is not very convenient, let's see if we can make this better.

<img width="1278" alt="Screen Shot 2019-05-08 at 12 07 28" src="https://user-images.githubusercontent.com/10341541/57397484-06802e00-718a-11e9-8e66-a4a435f8c0a6.png">

We're going to need some UX opinions here, @jonong1972 

# Definition of Done
Node connectivity error is easier to read

**Comment by jonong1972** [comment]
It looks that currently we are utilizing the side drawer only for the Error message on this Nodes view. Since that is the only thing we are doing on this page, we may be able to just word wrap the whole message, and we can over the whole side drawer with the message.

Looking at the code, for this particular context, we would have to put a CSS style on the pre tag.

white-space: pre-wrap;

Which would then show the error like this:

![Screen Shot 2019-07-29 at 2.16.41 PM.png](https://images.zenhubusercontent.com/5c58b40f704a793fa6c8d7b8/aba9ce28-4f7b-404f-806d-f707f571d1b3)
