### ISSUE TITLE
spike: chef infra change tracking (changelog) in automate

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3106]
## User Story

**this is a spike card.** the intention of this card is to find out, in a mostly definitive way:
- what a sample of two or three changes would look like (what is the change message)?
- how do we collect information about which machines succeeded and failed in making the change?
- is the information we can provide, given our current data model, sufficient to be helpful to the user?

**endpoint requirement details:**
- collect information from incoming reports about changes that have occurred across the fleet, assigning some kind of meaning to those changes. 
- return the list of changes that have occurred across the fleet, and how many machines successfully implemented the change/how many failed to make the change. list should be sortable.
- given a change, return the list of machines that have successfully made the change and a list of machines that failed to make the change.

**corresponding ux design:**
<img width="935" alt="Screen Shot 2020-03-11 at 21 09 48" src="https://user-images.githubusercontent.com/10341541/76721567-1bacde00-6706-11ea-94f6-43fcfcd9bcdc.png">

## Definition of Done
can answer the following questions:
- what a sample of two or three changes would look like (what is the change message)?
- how do we collect information about which machines succeeded and failed in making the change?
- is the information we can provide, given our current data model, sufficient to be helpful to the user?

**Comment by danielsdeleo** [comment]
# Proposal to Use Policyfiles for This

## Discussion of Semantically Rich Change Visibility

In the UI mockup, it shows the progress of changes with names like "screensaver policy" or "full disk encryption enabled." There is not any great way to model things at this level in Chef Client currently:
* A "single change" may require several resources to implement, for example writing config to disk and issuing a command to apply it immediately. The only real way to group them is to write a custom resource (e.g., a `screensaver` resource), but:
* Custom resources are an advanced topic in Chef; it would increase the perceived difficulty if we require users to write them in order to have visibility. Even so:
* There isn't any way currently to annotate Chef Infra resources (builtin or custom) with a description like shown in the UI mockup. We could add something like that, but still:
* We still need some other way to track the time component of each of these things in order to show the most relevant ones. For example, a screensaver policy introduced 2 years ago will still show up in the data when applied to newly purchased hardware. You'd want some other way to inform automate that on a given date, IT decided to turn on the screensaver, and, on a later date, set all screensavers to 10 minutes. If we were to implement the ability to annotate Chef Infra code like that, it should be automatic or automate-able so it doesn't rely on a person filling in some form every time (that they might forget or choose not to do). Making this information built-in probably requires more extreme changes elsewhere.

Compared to the above, Inspec works really well for this kind of thing. Inspec is designed to include semantic information describing the purpose of the specs, in the specs. However, just using Inspec instead of annotating Chef Infra code doesn't handle the time component. Users will still want to know what percentage of users have run the latest code and whether there were failures applying it. My opinion is that this is best handled by requiring desktop users use policyfiles, tracking changes to policyfiles over time, and correlating observations about Chef Client run outcomes with policyfile changes. Later we should add an Inspec component to the desktop offering that can tell in absolute terms how well the fleet is complying with desired standards. 

## Remedial Policyfile Basics:

Policies are specified in a ruby DSL that functions similar to Berkshelf; during development, policies and their associated tools function as a cookbook dependency manager (like bundler does for rubygems). The process of resolving and installing dependencies is referred to as a "build" or "compile" step in some places. This process emits a lockfile in JSON format. This lockfile contains information on all the cookbooks contained in the transitive dependency solution, including a repeatable fingerprint of the cookbook content along with the name, version, and source. The system also generates a unique ID for the aggregate compiled artifact based on all of the content it contains, which is the `revision_id` of the policy. Policyfiles have a name that is user-determined but generally should describe what kind of system is managed by the policy.

You can think of compiled policies as similar to compiled habitat packages. Policyfiles conceptually compile all the Chef Infra code a Chef Client needs to run into a single package with a standardized manifest of the package content (the lockfile). When uploading/downloading policies to/from a Chef Server, Chef Server and the client software use knowledge of the manifest (lockfile) format to implement some partial caching optimizations, but you can completely ignore these for the purpose of this discussion.

When using a Chef Server, compiled policyfiles are pushed to _policy groups_, which are like channel subscriptions in artifactory or habitat; they function as abstracted version pins to control the release/lifecycle of compiled policyfile revisions.

One of Chef's customer architects has training content that may be useful to get acquainted with any details you need clarity on: https://github.com/anthonygrees/policyfiles_training

## Code Lifecycle in Policyfiles

When using policyfiles, all changes to the Chef Infra code that a particular node has/will run occurs via assignment of a new revision id of a policy (name) to a policy group.

For example: let's suppose that ACME corp has only one variant of their Chef Infra code to manage their desktop fleet. They define the run list and dependencies in a policy named `desktop`. When they have new changes, they test them first in the `lab` policy group, and if that is successful they push the changes to the `beta-testers` group and finally to `everyone`. 

If ACME is using a Chef Server, they would do something like:

1. Do local development in test kitchen or whatever
2. When all the cookbook changes have gone through the desired process (lint, testing, review, etc.), run `chef install` to (re)compile the policy and commit the lockfile to git. Let's call this policy revision `123abc` and the one from previously `000000`.
3. Push this revision to the `lab` policy group. Now they have a policy revision table like this:
```
lab    | beta-testers | everyone
123abc | 000000       | 000000
```
4. Test the change in the lab. If it looks good, push (i.e., promote) the policy revision to the `beta-testers` policy group. The revision table will now look like:
```
lab    | beta-testers | everyone
123abc | 123abc       | 000000
```
5. If everything looks good for the beta testers, push (i.e., promote) the policy to the `everyone` policy group. The result will be
```
lab    | beta-testers | everyone
123abc | 123abc       | 123abc
```

## Policyfile-based Change Tracking in Automate

As described above, we can't model the rollout of changes at the "screensaver set to 10 minutes" level with policyfiles. What we can model is:
* which nodes have run the latest code for their group?
* how many Chef Client runs with this version of the code are failing total?
* how has this change affected Chef Client success compared to the previous code?
  * Chef went from success on previous run with the old code to failing now: you mighta broke it
  * Chef went from failing on previous run with old code to success now: you fixed it!
  * Chef went from success to success: your Ci is good :)
  * Chef went from failing to failing: sorry, mate.

We could also filter other information by policy revision. For example, what are the top N errors for a given revision of the policy?

If we have the policyfile (lock) content itself, we can compare two versions. The `chef` CLI has a `diff` command that compares two policy revisions you can look at for inspiration. The following things seem useful to highlight IMO:
* cookbook up/down-grades -- cookbooks in the policy that have different versions
* attribute changes
* run list changes

See also: https://github.com/chef/chef-cli/blob/1d9fc9f6a12c386bbfe477ceb7c78678f656315a/lib/chef-cli/policyfile/differ.rb

### What It Might Look Like:

User publishes revision `123abc` of the `desktop` policy to the `lab` policy group, the previous revision was `000000`.

The UI may have text like this:

Rollout of revision `123abc` of `desktop` policyfile to `lab` node group:
* 63% of nodes in the lab group have run this revision of the policy
* 5% of nodes running this revision of the policy failed to complete the latest Chef Client run. The top 3 errors were:
  * error a:
  * error b:
  * error c:
* 17 nodes that were previously failing are now succeeding
* 8 nodes that were previously succeeding are now failing
* 3 nodes that were previously failing are still failing

### "Future Proofing"

Generally I am against "future-proofing," since most of the time "ya ain't gonna need it." But I would encourage us to create an implementation that could be adapted for the effortless pattern.

**Comment by vjeffrey** [comment]
thanks for doing this writeup dan! 

we can consider the "spike" complete -- i'll open a separate issue for doing the actual work for this in automate
