### ISSUE TITLE
Data feed object is not updating. 

### ISSUE THREAD

**Issue by vinay033** [chef/automate#3246]
## Describe the bug
when you trying to update the data feed object then you are not able to update it. you are getting the error in API response like 
```
{"error":"error authorizing action \"datafeed:destination:update\" on resource \"datafeed:destination:\" filtered by projects [] for members [\"team:local:admins\" \"user:local:admin\"]: rpc error: code = InvalidArgument desc = invalid ProjectsAuthorizedReq.Resource: value does not match regex pattern \"^[a-z][^:*]*(?::[^:*]+)*$\"","code":7,"message":"error authorizing action \"datafeed:destination:update\" on resource \"datafeed:destination:\" filtered by projects [] for members [\"team:local:admins\" \"user:local:admin\"]: rpc error: code = InvalidArgument desc = invalid ProjectsAuthorizedReq.Resource: value does not match regex pattern \"^[a-z][^:*]*(?::[^:*]+)*$\"","details":[]}
```  
## To Reproduce
1. this is feature flag so you have to enable it
2. go to `settings` tab and click the `data feed` on left nav (`https://a2-dev.test/settings/data-feed`)
3. Create the data feed 
4. click to created data feed object and go to details page where you can update this object.

## Expected behavior
expecting the data feed object will be updated (https://a2-dev.test/settings/data-feed/form/{:id})
also, we need a response like 
```
{
  success: true
  id: "1"
  name: "feed1"
  url: "http://requestbin.sjcmmsn.com/ys9bp7ys"
  secret: "96f299bd-5224-48a5-91fb-09c2e14e5780" 
}
```
## Screenshots
![Screenshot from 2020-03-30 22-21-19](https://user-images.githubusercontent.com/12297653/77949340-66bd1880-72e4-11ea-9efc-450c13ab453c.png)

## Additional context
if possible please make changes in CREATE API response as well. currently, we are getting in response.
```
{
   success: true
}
``` 
expected response
```
{
  success: true
  id: "1"
  name: "feed1"
  url: "http://requestbin.sjcmmsn.com/ys9bp7ys"
  secret: "96f299bd-5224-48a5-91fb-09c2e14e5780" 
}
```

**Comment by bcmdarroch** [comment]
The issue here is that the resource's ID is not being populated:`resource \"datafeed:destination:\"`. I'm not sure yet whether this is an issue at the UI or gateway level, that'll require some more digging.

**Comment by satellite15** [comment]
I have reproduced this and I am investigating

**Comment by satellite15** [comment]
I get an error using the API directly and from the UI. In the UI request the id is present. This was working on the 23rd March when I updated the GRPC response for create and update. I'm guessing something has changed in IAM since then which is causing this. I think someone with IAM experience should investigate this. I thought possibly the update policy should have been 
resource: "datafeed:destination:{id}" 

instead of resource: 

"datafeed:destination/{id}" 

 but  I still got the error after changing and compiling the protobufs, and relevant services.

```
	  option (chef.automate.api.policy) = {
		  resource: "datafeed:destination/{id}"
		  action: "update"
	  };

**Comment by susanev** [comment]
On March 23rs was it working on both IAM v1 and v2?

**Comment by satellite15** [comment]
> On 23rd March was it working on both IAM v1 and v2?

I'm not sure, it was working from the UI and with direct API calls using an api-token for the admin user

**Comment by bcmdarroch** [comment]
The issue seems to be that the type of the `id` in the datafeed update request is `int64` and the code that generates the resource string can't interpolate it in the resource string. So an easy fix would be to change the id type to `string`.

We could also consider updating the code the generation code to stringify any non-string IDs.

One mystery: DeleteDestination seems to work fine, and it also defines `id` as type `int64`. My guess is that since there's no request body, the generation code looks instead to the URL for the id, which is in string format.

**Comment by bcmdarroch** [comment]
I think the quick bandaid option is to change the `id` in UpdateDestination to type `string`.

A slightly more in-depth, long-term solution:
- update our resource generator code to handle non-strings: https://github.com/chef/automate/blob/master/components/automate-grpc/protoc-gen-policy/policy/policy.go#L311

An even more in-depth, expensive, long-term solution: 
- do away with resources, since in IAM v2 projects have essentially replaced them

**Comment by satellite15** [comment]
@bcmdarroch I'll put up a PR for the bandaid solution. I don't believe it's worth considering the other options at this time. Thanks very much for your help in identifying the cause of this.
