### ISSUE TITLE
ui: weird/inaccurate filtering results on compliance node details

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3277]
## User Story
There have been a couple reports from customers about, for example, landing on the compliance reporting node detail page and seeing 4 results in the list where there should have been 6 according to the counts:
![image](https://user-images.githubusercontent.com/10341541/78310580-9c901600-750b-11ea-91ec-4e8c23aea1a7.png)

I haven't been able to reproduce this with the failures, but have seen it with waived controls:
<img width="1215" alt="Screen Shot 2020-04-02 at 17 54 37" src="https://user-images.githubusercontent.com/10341541/78310385-0e1b9480-750b-11ea-9af5-f5df9422a1be.png">

## Definition of Done
filter lists match the expected counts/report

## Demo Script / Repro Steps
`load_compliance_reports`
view node details on one of the compliance nodes
filter by waived controls

**Comment by SEAjamieD** [comment]
@vjeffrey - After digging around for a while in this, I think there may be some value in pairing on this with someone from API (superteam?). From what I can tell, the counts for each status, aren't being generated in the front end.

I located a couple different functions in some Go files that might help? but i'm not saavy enough in Go yet to debug, or really even just print out some statements.

looking at these helper methods:
https://github.com/chef/automate/blob/c98adce639629da5f33cc9031ab7acb522e48e7e/components/compliance-service/ingest/events/compliance/helper_methods.go#L40-L93

Or possibly in reports.go?
https://github.com/chef/automate/blob/master/components/compliance-service/reporting/relaxting/reports.go#L993-L998

Thoughts/opinions on this?

**Comment by susanev** [comment]
are we sure its the count that's wrong and not the list?

**Comment by SEAjamieD** [comment]
I went through the API response manually, and based on the response I'm seeing, the list is correct.

I looked at the response programmatically and printed as well:

<img width="703" alt="Screen Shot 2020-04-20 at 3 03 37 PM" src="https://user-images.githubusercontent.com/16737484/79804185-5d89ff00-8318-11ea-9195-34be1dc35a6b.png">


<img width="266" alt="Screen Shot 2020-04-20 at 3 04 31 PM" src="https://user-images.githubusercontent.com/16737484/79804200-65e23a00-8318-11ea-9b99-66ef719138fd.png">

**Comment by vjeffrey** [comment]
ya -- you're right -- this is a backend issue - thank you!

**Comment by rickmarry** [comment]
waived controls take come in two varieties:
1) the control is waived but it is still run.  In this case, it comes back with a waived_str of "yes_run"
2) the control is waived and not run.  In this case, it comes back with a waived_str of "yes"

In either of these cases, we should be counting controls with waived_str as being "waived" and the clickable rectangles above the list of controls in the example above are showing the correct numbers.

the problem is that the list below it is only considering controls with waived_str of "yes" to be waived and therefore showing incorrect statuses and also selecting them erroneously for display for the same reason. 

this filtering and setting of status badge for the list of controls happens in the front end

the fix is for the front end to consider controls with waived_str of "yes" or "yes_run" as being a waived control when filtering the list as well as when setting the badge for the list item.

**Comment by vjeffrey** [comment]
i think the changes need to happen in:
```
  getControlStatus(control): string {
    const statuses = control.results.map(r => r.status);
    const waived = control.waiver_data && control.waiver_data.skipped_due_to_waiver;
    if (waived) { return 'waived'; }
    if (statuses.every(s => s === 'passed')) { return 'passed'; }
    if (statuses.every(s => s === 'skipped')) { return 'skipped'; }
    return 'failed';
  }
```
in stats.service.ts

**Comment by SEAjamieD** [comment]
thanks for digging that out!  I can patch this up tomorrow morning
