### ISSUE TITLE
Use of the word "Successful" is problematic in the Client Runs views

### ISSUE THREAD

**Issue by tas50** [chef/automate#3347]
## Describe the bug
Using Automate client runs view for the first time is really confusing as the wording we use here does not align with the wording we use in Chef Infra Client or our documentation. We're breaking the resource updates into 4 states:

- Failed
- Successful
- Unchanged
- Unprocessed

![image](https://user-images.githubusercontent.com/1015200/79157747-ff927000-7d89-11ea-8f4d-7f3f468fea67.png)

The word successful here is SUPER problematic because it implies the unchanged things are not successful. Unchanged resources are 100% a success state. We're taking a system from a current state to a desired state and if that involves a state transformation or not it is a success. In the ideal world Chef Infra Client runs and dozens of resources do absolutely nothing. That's a success and our current wording doesn't reflect that.

## To Reproduce

View a Client view in the Infrastructure view.

## Expected behavior

In Chef Infra Client we often talk about how resources "update" or "converge". If someone is familiar with our platform or reads through our docs they're going to expect wording like that.

These are the states a long time Chef Infra user would expect:

- Failed
- Updated
- Unchanged

**Comment by susanev** [comment]
@tas50 do i understand correctly that changing `Successful` to `Updated` might help address this issue?

@vjeffrey unprocessed means failure without even starting? do i understand that correctly? if yes, we could prolly come up with a better label to describe that.

**Comment by susanev** [comment]
also, do yall have a word to describe updated + unchanged? because i think that's what the successful words in the run summary represent.. would `finished` work there? or any other ideas? 

this is what i have so far, what do you think?
<img width="934" alt="client-runs" src="https://user-images.githubusercontent.com/5489125/79225584-cdc4ec00-7e11-11ea-95d2-13702f5dda01.png">

<img width="1091" alt="node-detail" src="https://user-images.githubusercontent.com/5489125/79225578-cb629200-7e11-11ea-8fd9-3eb65df38413.png">

**Comment by tas50** [comment]
"Updated" would probably make a lot more sense to most operators. We shouldn't get into a scenario where we have something currently considered successful but in an unchanged state for *resources*. Chef Infra Client runs are a whole different beast and in that case things are either successful or failed. The run completed successfully and it updated a series of resources defined on the system.

**Comment by chef-davin** [comment]
So, you do have "Successful" nodes in a chef client environment - when the converge completes successfully.  I wouldn't change the Node status in the pie chart.  We might have pulled the "Chef client converge completed successfully" out of the messages at the end of the client run, but being an operator since client 12, I still think of a converge being either fatal, or "successful".  I would not change the node pie chart in any way.  Especially since this isn't targeted at operators. You're targeting managers and executives that want data. If you're nodes are converging, that's success because it means you're maintaining them to standard. If you change that to "Updated", you're going to have people ask "What are you updating?", or "Did those updates go through the change review board?".

That said. In terms of resources.  I think having "Successful" be "Updated" or "Modified" is fine.  Because at the resource level, that's what's happening. It just isn't the way I'd portray it at the node level.  I'd honestly love to see it as "Triggered", as that's essentially what you're doing.  But if you want to get real detailed, it'd be nice to see resources that are skipped separated by "up to date" or "not if" reasons, but I don't know if that data is even in the data feed.

I will say that I started as an operator just before Automate was released.  I didn't really look at Automate until you debuted A2 though, and I've never felt that the terminology on the infrastructure tab was at all incongruous. It can absolutely be better aligned, but I don't think it's especially confusing as it is.

**Comment by lamont-granquist** [comment]
@chef-davin I'll weigh in pretty strongly against "triggered".  That makes me think that it was as the result of a notification or subscribes or some other messaging event.  I don't think of resources that converge has having been "triggered" since there's no eventing mechanism that kicks off the update, its just the result of the resource doing a conditional evaluation of the state that the node is in.

The states that the action_collection in chef-client and the data_collector use are:

```
      # The status of the resource:
      #   - updated:     ran and converged
      #   - up_to_date:  skipped due to idempotency
      #   - skipped:     skipped due to a conditional
      #   - failed:      failed with an exception
      #   - unprocessed: resources that were not touched by a run that failed
      #
      # @return [Symbol] status
      #
      attr_accessor :status
```

The first 4 are used pretty consistently around the chef-client codebase, including in event handlers, etc that are customer facing.  The unprocessed state is pretty unique to the data collector itself and was invented for the purpose of publishing in to Automate 1.  I don't even know if users get value out of that.

**Comment by chef-davin** [comment]
I'm perfectly happy to not use triggered @lamont-granquist.  I think of it that way because the converge acts when the resource targeted is not in the desired state, therefore it's triggered by not being in the desired state.  But I know that's a generalization/innacurate way to look at it, it's just how I think of it myself.

**Comment by susanev** [comment]
this work has been deprioritzied
