### ISSUE TITLE
Missing proj ID on `Get` results in unauthorized 

### ISSUE THREAD

**Issue by blakestier** [chef/automate#3358]
[From another ticket:](https://github.com/chef/automate/pull/3312)

Fetching a rule with a missing rule ID gets a nice validation error 
```
[42][default:/src:0]# curl -kH "api-token: $TOK" https://a2-dev.test/apis/iam/v2/projects/neato/rules/ | jq
{
  "error": "a rule id is required and must contain at least one non-whitespace character",
  "code": 3,
  "message": "a rule id is required and must contain at least one non-whitespace character",
  "details": []
}
```
But fetching a project with a missing ID gets this error that's a bit of a red herring:

```
[47][default:/src:0]# curl -kH "api-token: $TOK" https://a2-dev.test/apis/iam/v2/projects/ | jq
{
  "error": "error authorizing action \"iam:projects:get\" on resource \"iam:projects:\" filtered by projects [] for members [\"token:admin-token-1586543035\"]: rpc error: code = InvalidArgument desc = invalid ProjectsAuthorizedReq.Resource: value does not match regex pattern \"^[a-z][^:*]*(?::[^:*]+)*$\"",
  "code": 7,
  "message": "error authorizing action \"iam:projects:get\" on resource \"iam:projects:\" filtered by projects [] for members [\"token:admin-token-1586543035\"]: rpc error: code = InvalidArgument desc = invalid ProjectsAuthorizedReq.Resource: value does not match regex pattern \"^[a-z][^:*]*(?::[^:*]+)*$\"",
  "details": []
}
```

**Comment by bcmdarroch** [comment]
This is getting at a core design issue in the gateway middleware: any field that is needed to create the resource and action pair for the IsAuthorized call must be enforced as required at the proto validation level. Without any required validation, IsAuthorized _does_ catch the error, but it provides a misleading message.

The problem is there is no easy `required` validator we can use. The closest approximate `min_length = 1` results in a weird error message about "runes". We could use a regex validator but that seems excessive for something like a Get request.

One solution would be to use the `min_length` validator (or maybe some other combo of validators) and wrap the error in our own message before sending it back to the user.
Ideally this solution should be implemented across our APIs.

**Comment by srenatus** [comment]
Some alternatives to fix this, I think, are

1. Creating out own PGV-compatible message validation in the gateway. I.e. for `CreatePolicyRequest`, we'd define `func (r *CreatePolicyRequest) Validate() error`, and opporunistically call that from the gateway middleware.

    We'd control the error messages. The validation wouldn't be proto-driven.

2. Since only the fields required for the authorization check matter in the gateway (architectural concerns aside!), we could enhance the generated code that does the lookup of those fields. When it encounters `""`, it could return an error instead of constructing what ends up being an invalid resource identifier.

I think both of these are similarly low-effort.

**Comment by susanev** [comment]
this work has been deprioritized.
