### ISSUE TITLE
check api docs examples

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#3597]
## User Story

we've had a few ppl report issues using the examples as listed in api docs; let's give them a once over and see if we can get this cleaned up.
example: https://github.com/chef/customer-bugs/issues/161

**Comment by susanev** [comment]
@srenatus had also brought up the ability to pass data to a get request which might make this easier for folks since client runs and compliance work differently. @srenatus could you say more?

**Comment by srenatus** [comment]
Oh right! So, as far as I know, a request body with a GET request is uncommon but not impossible, and ES does it that way, too. To use the request body, you'd need `body: "*"` in the method options, like here: https://github.com/chef/automate/blob/master/api/external/ingest/chef.proto#L22-L25, but with the method option in question. (⚠️ I haven't tried this. But it could work! 😄)

(The other thing is that to curl to, you need to explicitly add `-XGET`, as `curl https://... -d "something"` will automatically use POST unless specified otherwise.)

**Comment by vjeffrey** [comment]
related: https://github.com/chef/automate/pull/3635/files
