### ISSUE TITLE
Question about introspect.

### ISSUE THREAD

**Issue by foresx** [chef/automate#3766]
Hello there, I'm new to chef community. And I learn quiet a lot good design thought from chef automate authz service abount opa. But still I have some questions especially about the instropect interface. 
  I know Chef have "project" concept, and I thought in introspect interface's response would show that info or maybe filter by "project" parameter in the request. I find that IntroAllReq and IntroAllResp's proto definition, I didn't see any info about project. 
  I really want to get some help to figure out  introspect interface design.
  please.

**Comment by foresx** [comment]
@msorens  maybe you could help out? I saw some pr about introspect that you did.

**Comment by msorens** [comment]
Thanks for the question. It is always fun to see people looking at our code!

Your observations are quite accurate. Introspection is not yet project-aware, mainly because we have not had a crucial need for it yet. It is in our backlog of work to do, though we do not yet have a specific delivery date at this point.

From your question, it sounds like you already have a good grasp of OPA and introspection, but if you want another perspective, here is a presentation I did at the OPA Summit at KubeCon 2019 that talks about both of them in detail:
https://www.youtube.com/watch?v=jrrW855xL3s&list=PLJHPZt__YGKeCg3Lew3jvCOuyiUhW25Sk&index=5&t=0s

By the way, it is fine to ask questions here in GitHub like this, but wanted to let you know that our [Chef Community Slack](http://community-slack.chef.io/) is available, too. 😁

**Comment by foresx** [comment]
> Thanks for the question. It is always fun to see people looking at our code!
> 
> Your observations are quite accurate. Introspection is not yet project-aware, mainly because we have not had a crucial need for it yet. It is in our backlog of work to do, though we do not yet have a specific delivery date at this point.
> 
> From your question, it sounds like you already have a good grasp of OPA and introspection, but if you want another perspective, here is a presentation I did at the OPA Summit at KubeCon 2019 that talks about both of them in detail:
> https://www.youtube.com/watch?v=jrrW855xL3s&list=PLJHPZt__YGKeCg3Lew3jvCOuyiUhW25Sk&index=5&t=0s
> 
> By the way, it is fine to ask questions here in GitHub like this, but wanted to let you know that our [Chef Community Slack](http://community-slack.chef.io/) is available, too. 😁

Thanks a lot, really like your sharing in the summit. I watched it before I ask this question, it's really good, useful and really help me a lot.  Thanks for replying this question again, I'll join the slack and ask question about chef in there in the future.
