### ISSUE TITLE
icons dont load sometimes in safari

### ISSUE THREAD

**Issue by susanev** [chef/automate#3984]
## overview
when using safari sometimes the icons dont load
investigate why and see if we can fix it
or at a minimum, if icons dont load hide them entirely instead of displaying the label

seems like it could be an issue with ligatures?
adding `text-rendering: optimizeLegibility` may help

![screen_shot_2020-06-24_at_3 50 32_pm](https://user-images.githubusercontent.com/5489125/85767574-0106df80-b6cd-11ea-9f21-326f02dd3731.png)

**Comment by ghenkhaus** [comment]
![Screen Shot 2020-07-01 at 9 11 49 PM](https://user-images.githubusercontent.com/7216836/86315748-cc6cb980-bbdf-11ea-9fb6-31a633c51187.png)

[Error] Origin https://demo-validator-a2.chef-demo.com is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://telemetry.chef.io/segment/api_keys due to access control checks.
[Log] Error retrieving Segment API key: 0/undefined (main-es2019.16d125b6df3242c1fba9.js, line 1)
[Error] Failed to load resource: Origin https://demo-validator-a2.chef-demo.com is not allowed by Access-Control-Allow-Origin. (api_keys, line 0)
> Selected Element
< <header>…</header>

**Comment by ghenkhaus** [comment]
I have notice that clearing the browser cache has resolved the issue temporarily.

**Comment by susanev** [comment]
folks think this may be related to...
https://github.com/panthershark/safari-cache-bug

**Comment by Shadae** [comment]
Closing due to Safari cache bug stated above
