### ISSUE TITLE
elasticsearch version upgrade

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#4165]
## User Story

We are getting close to the EOL for our current elasticsearch version (6)
https://www.elastic.co/support/eol

We'll need to upgrade to ES 7 or 8 by end of year

## Considerations
Automate 1 is on ES 5 - ES only supports upgrades of 2 versions or less, so we'll need a plan for automate 1 folks upgrading
Opsworks?
We'll need to coordinate/talk with the folks that take care of ha stuff

Aha! Link: https://chef.aha.io/epics/SH-E-258

**Comment by thomascate** [comment]
Here's a minor thing that will mostly effect a2-ha-backend.
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#:~:text=Index%20creation%20no%20longer%20defaults,now%20one%20shard%20per%20index.
Basically it now defaults to 1 shard per index instead of 5. For standalone this is probably better, but for distributed installs you want something higher.

We could fix this by adding a shards and replica setting to any index templates we make. Then just pass a tunable through so a2-ha-backend can tweak it if needed.

**Comment by vjeffrey** [comment]
looks like olivere has a 7 release but not 8 https://github.com/olivere/elastic/tree/release-branch.v7

**Comment by tas50** [comment]
Replaced with https://github.com/chef/automate/issues/5744
