### ISSUE TITLE
include error msg on client runs csv export

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#447]
# User Story

when downloading node reports to csv from the client runs tab, i would expect to see an error message on failed runs, but no such luck!
let's add in the error message so users know _why_ the run failed

# Definition of Done
error message is included in the run report for a failed ccr when exporting to csv

# Related Resources
https://github.com/chef/automate/issues/178

**Comment by lancewf** [comment]
The reason the error message is not in the CSV is because it is a struct. https://github.com/chef/automate/blob/master/components/config-mgmt-service/grpcserver/node_export.go#L61. 

We will have to add a new `ErrorMessage` field to the above `displayNode` struct and fill it with the newly added Node field from this PR https://github.com/chef/automate/pull/415/files#diff-3b1753e4fe9f90034d861041b6dbf6e5R34.

**Comment by aaronherman** [comment]
When will this get released as a new version of Automate? :)

**Comment by vjeffrey** [comment]
~ sometime in early July
