### ISSUE TITLE
`EOF` bug on compliance/profiles

### ISSUE THREAD

**Issue by susanev** [chef/automate#456]
## Overview
in acceptance (not current)
navigating directly to `compliance/profiles`
or refreshing that page once you're there results in a `EOF`

## What it looks like when its done
- change route to `compliance/compliance-profiles`
- this will need to be updated throughout the docs as well
    - https://automate.chef.io/docs/asset-store/#using-the-asset-store
    - https://automate.chef.io/docs/asset-store/#about-the-profile-identifier
    - https://automate.chef.io/docs/asset-store/#api-calls

**Comment by srenatus** [comment]
We've got a clash here:

a) automate-load-balancer config:
https://github.com/chef/automate/blob/master/components/automate-load-balancer/habitat/config/nginx.conf#L199-L204
b) new compliance ui route: https://github.com/chef/automate/pull/291/files#diff-fc147971f13617ccf3d96c5f26ef3f2aR227

If you navigate, no request is really sent (UI routes are a bit of a scam), **but** if you refresh, or browse directly, the browser sends a request to that path - and the load balancer will forward the request to the API endpoint. The request sent isn't good, so you'll get a bad response, which in this case is EOF.

I _think_ we cannot change (a) as too many clients (inspec, audit cookbook) depend on this exact API route (which is why the redirect exists in the first place, i.e., it's not a route below `/api/v0/...` etc). However, we could change (b) easily, I suppose

**Comment by srenatus** [comment]
Looking at the logs while accessing `https://a2-dev.test/compliance/profiles` _directly_, I only find
```
+ echo '[2019-05-31T12:33:52+00:00]' 'automate-load-balancer.default(O): - [31/May/2019:12:33:52 +0000]  "GET /compliance/profiles/ HTTP/1.1" 400 "0.001" 4 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "10.0.2.15:2000" "400" "0.000" 738'
```
which is a bit odd -- I'd have expected _some_ domain-service response there.

This is the handler that it hits: https://github.com/chef/automate/blob/7a5a2ecdd871ddf9098bf4274ffd0f2a4b241aa1/components/automate-gateway/gateway/server.go#L393 and https://github.com/chef/automate/blob/b5f7576a4aa8b48944abfa17d6953e1c4cd60c9e/components/automate-gateway/gateway/services.go#L331 -- and looking at *that code*, it really doesn't log much if there's any kind of bad request coming in. Basically, the `EOF` is what
```go
http.Error(w, err.Error(), http.StatusBadRequest)
```
looks like from a browser 😉
