### ISSUE TITLE
Netlify failing on every PR

### ISSUE THREAD

**Issue by msorens** [chef/automate#4697]
## Describe the bug

1. Netlify: "Deploy did not complete for chef-automate" -- this message is being generated for every PR for some weeks now.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/6817500/106662505-50f92f00-6557-11eb-93ba-f7d3e7063717.png">

## To Reproduce
Open a PR. Observe a failure notification posted in #a2-notify in slack.

## Expected behavior
Process should run to completion.
Successful output of Netlify manifests as ?? (I think docs-team can supply this detail.)

**Comment by IanMadd** [comment]
I shut off Slack notifications in a2-notify. 

The underlying issue is that Netlify won't make a build preview if there are no changes in `components/docs-chef-io`. Any build that isn't completed is classified as a failure and so we get the warning above. They do have a feature request in for changing notification, but who knows when that will happen.
