### ISSUE TITLE
Issue for CMDB app for IHG customers 

### ISSUE THREAD

**Issue by punitmundra** [chef/automate#4766]

**Comment by punitmundra** [comment]
1." Serial number" field length in the "Asset Import" table is set to 50 characters. Our servers have a length of approx. 60 characters. So when transforming the data from the staging table to CMDB Tables., the full serial number is not getting updated and is trimmed. I tried to increase the length multiple times and failed.

2. In the transform map OnBefore Script collects model_category at line number 10. In fact, there is no model_category field in the staging table Which affects in the creation of models.

**Comment by vivek-yadav** [comment]
This is fixed in the new Version of Chef Automate Integration App released.
Version: 2.0.1       [App Link in the Store](https://store.servicenow.com/sn_appstore_store.do#!/store/application/4cd4b300db68e700197478fdaa961908/2.0.1?referer=%2Fstore%2Fsearch%3Flistingtype%3Dallintegrations%25253Bancillary_app%25253Bcertified_apps%25253Bcontent%25253Bindustry_solution%25253Boem%25253Butility%25253Btemplate%26q%3Dchef&sl=sh)
