### ISSUE TITLE
Terraform changes for provisioning and deployment code split

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5403]

**Comment by meet58** [comment]
**Description**

Need to split deployment in 2 stage. 1st creation is sepratad and deployment(including installtion of hab pkg, airgap bundle, configuring database) should be seprated. Creation part includes the instance creation including netoworking and all other parametres. 2nd part using that instance parameters, deployment part should be triggered. To achive this need to first change terraform codebase because in current scenario creation and deployment is combined. So need to work on first terraform code sepration task.


**Acceptance Criteria**

automate-cluster-ctl should have a capability to create only infra based on a2ha.rb file's input.

**Comment by meet58** [comment]
This ticket is part 1 so not merged changes in master but created provision-deployment branch from master and again created provision branch from provision-deployment. https://github.com/chef/a2-ha-backend/pull/497 this pr is related to infra provision so I have pushed my changes in provision branch and that branch is merged in provision-deployment. Once deployment part is done that we can safely merge the provision-deployment branch into master.
