### ISSUE TITLE
Implement validation script based on the approach

### ISSUE THREAD

**Issue by karunesh-tech** [chef/automate#5511]
## Description
Work on the script for below use-cases using net-cat hab package:
make the changes for validation script:
- 		Port Blockage check 
- 		Internal connection check PG and ES 
- 		Number of server in config vs actual check

## Acceptance Criteria 
End to end completion of basic validation script

**Comment by meet58** [comment]
This is the PR link for validation script. https://github.com/chef/automate/pull/6366.

Work is in progress

**Comment by jayvikramsharma1** [comment]
one extra day of effort is remaining.

**Comment by meet58** [comment]
**Created Docs**: https://progresssoftware-my.sharepoint.com/:w:/r/personal/mgadhiya_progress_com/_layouts/15/doc2.aspx?sourcedoc=%7Bc5c9acfd-2b0a-4613-884e-17d3f896b9a4%7D&action=editnew&wdPreviousSession=a8edc7f9-ba07-cf1c-e8af-526cfeffde45&wdNewAndOpenCt=1639729312688&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=fa030879-88bd-4e59-8006-2293a450c48c

**Comment by meet58** [comment]
We are going to make saprate command in chef-automate instead of standalone script. So as part of that activity I am closing this ticket. This doc os ref for that new validate command. https://progresssoftware.sharepoint.com/:w:/r/sites/ChefCoreC/_layouts/15/Doc.aspx?sourcedoc=%7B8FB5DC33-B3E1-4515-9067-7289DBBDE722%7D&file=Validation-script.docx&action=default&mobileredirect=true&cid=de3c8bba-ae2c-43ce-8b95-d171ce54b4be.  
New ticket for this is https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/6439
