### ISSUE TITLE
Search/Filter API

### ISSUE THREAD

**Issue by danielsdeleo** [chef/automate#769]
# Description

Update applications APIs so that we can search/filter by the following:
* Service Name, e.g., "nginx"
* Package name, e.g., "core/nginx"
* Origin, e.g., "core"
* Group Name (service group name suffix after the '.')
* version, e.g., "1.2.3"
* Release (sem-ver/buildstamp)
* Environment
* Application (note that Deployment == Environment + Application)
* Channel
* Site
* Health Check Message

When filter criteria are present in a request to the service groups API, only services that meet the filter criteria are shown:

If all services in a service group match the filter criteria, the data presented in the row is identical to what is shown without filtering.

If no services in a service group match the filter criteria, the service group is not included in the response.

When some services in a service group match the filter criteria and some do not, the service group is presented as if it only contains the matching services. For example if a service group contains 3 services with site "Seattle" and 5 services with site "London," then when the filter query specifies `site=="Seattle"`, the mini-donut chart, "M of N OK" text, and release information should only show the three services which have `site=="Seattle"`.

Likewise the services API (the one that provides data for the right side panel) only returns services that match the filter criteria.In the previous example, only the three services where `site` is "Seattle" would be returned.

## Excluded:

* UI work will occur last
* An API to provide search suggestions for the search bar will be created later

# Demo:

curl the service groups API, maybe use jq to make it easy to see that all the things are returned. Add search parameters to the request and show that only matching things are returned. For completeness, the demo should show cases where:
* all services match the filter criteria and the response is unchanged compared to an unfiltered response
* no services match the filter criteria and the response contains no services/service groups
* some services match the filter criteria and the number of results and associated fields (health counts for the mini-donuts, etc.) are modified to match
* Some services match the filter and the services sidebar is filtered appropriately to show the matching services

**Comment by afiune** [comment]
I have an idea to tackle this work, that is to bring back the main service-group select query.

The idea behind here is that we can put back the main select that we moved to be a view
so that you can inject the filters through WHERE statements, these statements can be composed
in the same manner we are building the WHERE statements in the `services.go` file at:
=> https://github.com/chef/automate/blob/master/components/applications-service/pkg/storage/postgres/services.go#L241-L258

I have an open PR to show the idea and to talk through this solution, also please feel free to take over this branch and continue the development if this sounds like the right way to go.
