### ISSUE TITLE
Chef Automate Applications tab mixes UTC and server's Timezone 

### ISSUE THREAD

**Issue by ericcalabretta** [chef/automate#972]
When you drill down into the applications tab and the details bar on the right on the screen the time is computed incorrectly if the servers timezone isn't UTC. 

For this screen shot the supervisor was actually loaded 7 minutes ago and not 5 hours and 7 minutes. 

The Automate server is in Central Time, and it looks like the apps tab is using UTC to compute the "since the service" time 

![Screen Shot 2019-07-19 at 11 30 03 AM (1)](https://user-images.githubusercontent.com/22911544/61553194-809d2080-aa1f-11e9-8b73-2eac10163ec9.png)

**Comment by danielsdeleo** [comment]
I'm only able to partially reproduce this. The timestamps I'm seeing in the tooltips are incorrect. The "time since" values are correct.


Here's what I've tried and the results I have gotten:

First I confirmed that changing the `TZ` variable will change a go program's timezone by running the following go code with `go run` with different settings of `TZ`:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(time.Now().String())
}
```

Next I set `export TZ=America/New_York` in the studio and started all the services. I am in PDT currently so 

I verified that the TZ variable was set for Postgres and applications-service by checking `/proc/$pid/environ`, e.g., `xargs -0 -L1 -a /proc/2993/environ | grep TZ` for Postgres and applications-service.

I checked Postgres' timezone with:

```
chef-automate dev psql chef_applications_service -- -c "SELECT * FROM pg_timezone_names WHERE abbrev = current_setting('TIMEZONE');"
```

The result of that command indicates Postgres is using UTC anyway. Based on some googling, it seems that pg will use UTC unless explicitly set in the config file; it ignores the `TZ` variable. The customer affected by this bug had the same result on their machine, so we can rule out timezones in the pg server as a problem.

When I use the data generator we typically use for development, `applications_populate_database`, I don't see the same behavior reported here.

I ran the generator at 14:13 PDT (21:13 UTC) on July 23. When I view the applications page shortly after, the "timewizard" says "Since the service was loaded, 8 seconds ago," which is correct. However, the tooltip that appears when I hover over the text says "July 23, 09:13 UTC" which is incorrect. When I use the web inspector to see the JSON content of the XHR, I see values of `health_updated_at` like `2019-07-23T21:13:25.009413Z`, which is correct.

The data generator we use for development is a totally different codebase to the habitat client though. So I next used the docker-based hab client testing setup from here: https://github.com/chef/automate/tree/master/components/applications-service/dev/hab-client

I modified the Dockerfile with:

```
ENV TZ="America/Denver"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

This sets the timezone to one that's different from mine and the one I set on Automate.

When I run the `run-hab-sup.sh` script at 14:26 PDT (21:26 UTC) and check the applications view shortly after, I again see that the time difference text is correct, it reports "Since the service was loaded, 38 seconds ago." The timestamp reported when I hover is incorrect, though, it's giving 09:26 UTC, but the `health_updated_at` field is `2019-07-23T21:26:49.211427Z` in the JSON document in the web inspector.

**Comment by danielsdeleo** [comment]
I found a formatting error in the way we display the time that was showing the 12-hour time instead of 24, which accounts for the discrepancies I was seeing, but not the ones reported in the bug report.

**Comment by danielsdeleo** [comment]
I'm unable to reproduce this on Windows, so I am out of ideas to reproduce this.

In attempting to repro, I created an Automate instance on EC2 following the normal instructions, except I installed packages from the dev channel. I then created a Windows 2019 client in EC2 and set the timezone to CDT. I verified in the powershell console:

```
PS C:\Users\Administrator> timezone


Id                         : Central Standard Time
DisplayName                : (UTC-06:00) Central Time (US & Canada)
StandardName               : Central Standard Time
DaylightName               : Central Daylight Time
BaseUtcOffset              : -06:00:00
SupportsDaylightSavingTime : True
```

I started the hab supervisor in the same powershell window, and then ran `hab svc load core/nginx` in a new window. The reporting of the time that the service was loaded in the service detail panel is still accurate and definitely not offset by hours.

**Comment by anthonygrees** [comment]
I have a customer in NZ that hits this issue as well.  At 12pm NZ the compliance for the day disappears in the automate UI ! Automate thinks it's the next day. The system time is correct at NZST.

I'm happy to help reproduce this issue !  And I'm certain my customer will be happy to show you and help solve it.

**Comment by sopii2003** [comment]
I'm based Sydney (+10) and work in a large organisation that also suffers from this.  
It's quite annoying for users to continuously reset the date in Automate UI to get a true representation of current state. 

we can also provide additional info if required.
